version: 2
updates:
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '13:00'
      timezone: 'Asia/Manila'
    open-pull-requests-limit: 99
    commit-message:
      prefix: 'feat(deps):'
      prefix-development: 'chore(deps):'
      include: 'scope'

  - package-ecosystem: github-actions
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
      time: '20:00'
      timezone: 'Asia/Manila'
    commit-message:
      prefix: 'ci(deps):'
      prefix-development: 'ci(deps-dev):'
      include: 'scope'
