require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - Gemfile*
    - gemfiles/*
    - spec/fixtures/rails_app/**/*
    - vendor/bundle/**/*

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Rails:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: true
  Exclude:
    - "lib/devise/auth0/rails.rb"

RSpec/DescribeClass:
  Exclude:
    - "spec/integration/logout_spec.rb"
    - "spec/integration/omniauth_spec.rb"

RSpec/FilePath:
  Exclude:
    - "spec/devise/auth0/**/*.rb"
    - "spec/integration/strategy_spec.rb"

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/AnyInstance:
  Enabled: true
  Exclude:
    - "spec/devise/auth0/model_spec.rb"

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Exclude:
    - "spec/support/fixtures.rb"

RSpec/Rails/InferredSpecType:
  Exclude:
    - "spec/integration/*.rb"

RSpec/VerifiedDoubleReference:
  Enabled: false
