name: Changelog
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dangoslen/changelog-enforcer@v3
      with:
        changeLogPath: "CHANGELOG.md"
        skipLabels: "skip_changelog"
        token: ${{secrets.DEVOPS_GITHUB_TOKEN || github.token}}
